Repository commaai/panda, pull requests merged in 2022-09, with the labels that each got.

#939 Toyota: generic steer fault workaround safety
  board/safety.h
  board/safety/safety_gm.h
  board/safety/safety_toyota.h
  board/safety_declarations.h
  tests/safety/common.py
  tests/safety/test.c
  tests/safety/test_toyota.py
Labels: car safety

#1062 H7: remove manual bus off handling
  board/drivers/fdcan.h
Labels: refactor

#1061 CAN bus: adjust SJW and time quanta to SAE 2284-3
  board/stm32fx/clock.h
  board/stm32fx/llbxcan.h
  board/stm32h7/llfdcan.h
  tests/debug_console.py
Labels: fix

#1067 CAN: health message for each CAN module
  board/can_health.h
  board/drivers/bxcan.h
  board/drivers/can_common.h
  board/drivers/fdcan.h
  board/main.c
  board/main_comms.h
  board/stm32fx/llbxcan.h
  board/stm32h7/llfdcan.h
  python/__init__.py
  tests/automated/3_usb_to_can.py
  tests/automated/helpers.py
Labels: enhancement

#1077 Add the 0x600 range for UDS messages
  board/safety/safety_elm327.h
Labels: enhancement, car safety
