Repository commaai/panda, pull requests merged in 2023-07, with the labels that each got.

#1282 update old comment
  board/main.c
Labels: cleanup

#1496 safety_toyota: use GET_BIT
  board/safety/safety_toyota.h
Labels: cleanup

#1498 angle safety: make angle conversion factor a float
  board/safety/safety_ford.h
  board/safety_declarations.h
Labels: cleanup

#1380 Subaru: improve readability in panda code
  board/safety/safety_subaru.h
  board/safety/safety_subaru_preglobal.h
Labels: car safety, cleanup

#1505 Subaru: Use macros for gen1/gen2
  board/safety/safety_subaru.h
Labels: cleanup

#1508 Subaru: cleanup tests
  tests/safety/common.py
  tests/safety/test_hyundai_canfd.py
  tests/safety/test_subaru.py
Labels: tests, cleanup

#1511 safety helpers: cruise engaged prev setter
  tests/libpanda/safety_helpers.h
  tests/libpanda/safety_helpers.py
Labels: car safety, tests

#1497 SPI kernel driver
  .gitignore
  drivers/spi/.gitignore
  drivers/spi/Makefile
  drivers/spi/load.sh
  drivers/spi/patch
  drivers/spi/pull-src.sh
  drivers/spi/spi_panda.h
  drivers/spi/spidev_panda.c
  python/spi.py
Labels: enhancement

#1516 Ford: namespaced constants
  board/safety/safety_ford.h
Labels: cleanup

#1455 Ford CAN FD safety
  board/safety/safety_ford.h
  python/__init__.py
  tests/safety/common.py
  tests/safety/test_ford.py
Labels: enhancement, car safety
