Repository commaai/panda, pull requests merged in 2023-06, with the labels that each got.

#1446 H7: fix CAN RX delay
  board/drivers/fdcan.h
Labels: bugfix

#1431 H7: fix lockup on disconnected bus
  board/drivers/bxcan.h
  board/drivers/fdcan.h
  board/stm32h7/llfdcan.h
Labels: bugfix

#1459 Flash bounds checking outside of bootstub
  board/drivers/logging.h
  board/fake_stm.h
  board/stm32fx/llflash.h
  board/stm32fx/stm32fx_config.h
  board/stm32h7/llflash.h
  board/stm32h7/stm32h7_config.h
Labels: enhancement

#1461 Ford: don't check vehicle roll quality flag
  board/safety/safety_ford.h
  tests/safety/test_ford.py
Labels: car safety

#1482 query_fw_versions: sub-address support
  examples/query_fw_versions.py
Labels: enhancement, tools
