Repository commaai/panda, pull requests merged in 2023-01, with the labels that each got.

#1200 Reset CAN ign when the specific message is not seen anymore
  board/drivers/can_common.h
Labels: bug, fix

#1209 Panda: context manager support
  examples/query_fw_versions.py
  python/__init__.py
  tests/canfd/test_canfd.py
  tests/ci_reset_hw.py
  tests/hitl/1_program.py
  tests/hitl/2_health.py
  tests/hitl/helpers.py
  tests/pedal/test_pedal.py
Labels: cleanup

#1223 Add timeout to spi driver
  board/drivers/spi.h
  board/stm32fx/llspi.h
  board/stm32h7/llspi.h
Labels: enhancement

#985 Chrysler: increase torque rate limits
  board/safety/safety_chrysler.h
  tests/safety/test_chrysler.py
Labels: car safety
